// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSuP2gENHC6kwQHMW0mVY7s1E229-zZhs',
    appId: '1:906464238572:web:3e06211791f59e2318bec9',
    messagingSenderId: '906464238572',
    projectId: 'lane-dane-20615',
    authDomain: 'lane-dane-20615.firebaseapp.com',
    storageBucket: 'lane-dane-20615.appspot.com',
    measurementId: 'G-7E6EWN9E5B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvJOYwuAqpKxvukresV4fIv5jmojgmQoI',
    appId: '1:906464238572:android:edda55aefd899f3d18bec9',
    messagingSenderId: '906464238572',
    projectId: 'lane-dane-20615',
    storageBucket: 'lane-dane-20615.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSbxSjZSy7Weimkl5o9NPgqSeXu8MRor8',
    appId: '1:906464238572:ios:30a6ada2e0fc5b3c18bec9',
    messagingSenderId: '906464238572',
    projectId: 'lane-dane-20615',
    storageBucket: 'lane-dane-20615.appspot.com',
    iosBundleId: 'com.yash.leinDein',
  );
}
